# Configuraci�n para desarrollo (DEV)
server.port=8090

# Base de datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://92.112.176.191:5432/PROVEEDORES_TEST?options=-c%20timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=DarioDavid-bd-UBU-1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicializaci�n de Datos (data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
